version: '3'

services:
  db_postgres:
    image: postgres:9.6.15
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  admin_postgres:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 16543:80
    depends_on:
      - db_postgres
      
  rails:
    build:
      context: .
      args: 
        USER: $USER
    container_name: rails-container
    command: /bin/bash
    ports:
      - 3000:3000
    volumes:
      - $PWD:/docker
    depends_on:
      - db_postgres
